/** Design contract for the actual SDK renderers. Not a vendor certification. */
export const reviewSummary = [
  "One visual language: neutral color, a consistent type scale, aligned margins and a protected subtitle area. Footage carries the scene; graphics explain what matters.",
  "Readable at phone size: headlines, body and labels use fixed proportions. Long accepted copy moves across successive pages instead of shrinking into tiny type. Every character is retained.",
  "Quiet motion: short entrances, stable reading holds, one active comparison or milestone, and deliberate source-image focus. These reveals follow scene progress; they are not word-level narration cues.",
  "Subtitles in the live briefing use short phrases on a restrained dark backing. Their timing follows speech, without a second word-by-word color animation.",
  "The remaining editorial judgment is the footage itself: relevance, crop and shot variety still depend on the supplied material and provider output. A consistent renderer cannot guarantee a good film from arbitrary assets.",
];
export const templateReviews: Record<string, { verdict: string; finding: string; next: string }> = {
  cinemaMedia: { verdict: "Image first", finding: "Uninterrupted footage gives narration room. Both stock and generated clips can use this layout; it is now available to the media-led planner.", next: "Use a meaningful moving image. Keep display text off this beat; narration and live subtitles carry the detail." },
  chapterTitle: { verdict: "Opening / pause", finding: "An anchored headline, a short entrance and a stable hold. Long titles keep their type size and reveal in successive pages.", next: "Reserve for an opening or a genuine change of topic. Repeated generic title beats are eligible for a clean footage replacement." },
  textMedia: { verdict: "Everyday explanation", finding: "A lower-left headline and supporting statement over full-frame media, with local contrast and a separate subtitle area.", next: "Write one short claim and one supporting line. Pick footage whose important subject stays clear of the lower-left text." },
  keyFigure: { verdict: "Evidence", finding: "The figure remains the focal point. Its qualifier stays readable; unusually long accepted values are paged rather than shrunk.", next: "Prefer a short sourced value with its units and qualifier. Illustrative footage is not evidence for a metric." },
  comparison: { verdict: "Two deliberate beats", finding: "One side is visible at a time, with a small two-part position marker. The two paragraphs no longer compete for attention.", next: "Compare equivalent, supported facts. Keep both sides concise and allow the narration to explain the difference." },
  quote: { verdict: "Editorial pause", finding: "A restrained quotation and clear attribution share the same readable scale. Longer quotations move through pages without losing characters.", next: "Use an exact attributed quotation, sparingly. Choose a quiet image or a plain field so the words have a reason to lead." },
  editorialTimeline: { verdict: "Sequence", finding: "One active milestone and a quiet progress rail replace a crowded diagram. Each step has space to read on a phone.", next: "Prefer three brief milestones with a meaningful order. Progress follows the scene clock; do not imply exact word synchronization." },
  personalRelevance: { verdict: "Personal outcome", finding: "A small person label, one outcome and a supporting connection. The decorative colored card is gone; the person's work supplies the visual context.", next: "Use a concrete goal from the supplied brief. Do not invent a personal benefit or unsupported result." },
  screenshotSpotlight: { verdict: "Original evidence", finding: "An original source image establishes context, then a supplied focus region directs a close-up. Optional generated illustration is kept separate from source pixels.", next: "Supply a legible original and an accurate focus rectangle. Without a focus rectangle the renderer preserves the overview; it does not guess a UI target." },
  actionSteps: { verdict: "One next move", finding: "A single action is visible at a time, with a small count and progress rail. Supporting detail remains readable above the caption zone.", next: "Prefer two clear actions. Give each an owner or a decision criterion in the supplied content, and let the image support that action." },
};
export const selectionRules = [
  "Meaning first: the model chooses from nine editorial layouts plus a clean footage beat in media-led hybrid mode. Structure and copy bounds are validated; factual truth still depends on the supplied brief.",
  "Source imagery: a matching unused host screenshot can take priority. A pure footage choice becomes a screenshot spotlight when a matching source image is available. Explicit spotlight scenes must use a supplied asset ID.",
  "Variety: a third identical consecutive generic title or explanation can become pure footage only when its display copy is already in narration and contains no protected numeric or quoted facts. Specialized layouts, closers and source assets are preserved. This is a bounded rule, not a universal repetition ban.",
  "Footage: explicit stock requests are respected. Later eligible scenes may receive generated footage, with at most three clips per answer and the existing cost/deadline limits. Early and ordinary ending footage stays stock when available.",
  "Recovery: unavailable footage retains readable authored content. A clean footage beat without media becomes a chapter containing the scene title and narration. Source-image animation remains off in the demo configuration.",
  "Loading reuses the chapter renderer. Podcast and text are separate output views, not additional video templates. Gallery examples use existing media and never request new generation.",
];
